import { Link } from 'react-router-dom';
import { ShieldCheck,Wrench,Clock3,BadgeDollarSign,ArrowRight,Phone,CheckCircle } from 'lucide-react';
import HeroSlider from '../components/HeroSlider';
const services=[
['Fridge & Freezer Repairs','https://cdn6.ep.dynamics.net/s3/rw-propertyimages/2801-H3125076-99702774__1721265853-49151-DSC07954.jpg?anchor=middlecenter&format=jpg&height=640&maxheight=2841&maxwidth=2841&mode=crop&quality=75&scale=down&width=640','Cooling faults, leaks, thermostats, compressors, fans and door seals.'],
['Washing Machine Repairs','https://a0.muscache.com/im/pictures/hosting/Hosting-U3RheVN1cHBseUxpc3Rpbmc6MTA1NjQ4NjAxNTY1MTI4MTM4Mw%3D%3D/original/19aa75e9-4e44-4bc6-a422-16fbbd369aa4.jpeg?im_w=720','Drainage, spin-cycle, pump, motor, belt, bearing and electrical faults.'],
['Oven & Stove Repairs','https://cdn.shopify.com/s/files/1/0641/9388/8321/files/50097924_1046289.png?v=1776396808','Heating elements, ignition, temperature controls and electrical faults.'],
['Dishwasher Repairs','https://cdn.cocinaintegral.net/cocinaintegral/2024/05/FAGOR-LAVAVAJILLAS.jpg','Drainage, pump, inlet, heating, leaks and control problems.'],
['Air Conditioner Service','https://www.viessmann.be/content/dam/public-brands/fr/tout-savoir/technologies-chauffage/pompes-chaleur-air-air/3-2-vitoclima-confort.jpg/_jcr_content/renditions/original./3-2-vitoclima-confort.jpg','Cooling problems, servicing and common air-conditioning faults.'],
['Microwave & Other Appliances','https://images.rawpixel.com/image_social_landscape/cHJpdmF0ZS9sci9pbWFnZXMvd2Vic2l0ZS8yMDI1LTA0L3NyLWltYWdlLTA5MDQyMDI1LW1rbTA0LXMtMjI5XzEuanBn.jpg','Diagnosis and repairs for selected household and commercial appliances.']];
export default function Home(){return <div className="page-enter"><HeroSlider/><section className="bg-appliance-900 py-6"><div className="max-w-7xl mx-auto px-4 grid grid-cols-2 md:grid-cols-4 gap-5 text-white">{[[Wrench,'Expert Technicians'],[Clock3,'Fast Durban Response'],[ShieldCheck,'Reliable Repairs'],[BadgeDollarSign,'Affordable Pricing']].map(([I,t]:any)=><div className="flex gap-3 items-center" key={t}><I className="text-amber-400"/><span className="text-sm font-semibold">{t}</span></div>)}</div></section><section className="py-20 bg-appliance-50"><div className="max-w-7xl mx-auto px-4"><div className="text-center mb-12"><span className="section-tag">What We Repair</span><h2 className="section-heading text-center">Professional Appliance Repair Services</h2><div className="gold-bar mx-auto"/><p className="text-appliance-500 max-w-2xl mx-auto">Appliances Repair Solutions provides practical repair support for major household and commercial appliances across Durban and surrounding areas.</p></div><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-6">{services.map(([title,img,desc])=><Link to="/services" key={title} className="bg-white rounded-2xl overflow-hidden shadow-sm hover:shadow-xl transition"><img src={img} alt={title} className="w-full h-48 object-cover"/><div className="p-5"><h3 className="font-bold text-lg">{title}</h3><p className="text-appliance-500 text-sm mt-2">{desc}</p><span className="text-amber-500 text-sm font-semibold inline-flex gap-1 items-center mt-3">Learn More <ArrowRight size={14}/></span></div></Link>)}</div></div></section><section className="py-20 bg-white"><div className="max-w-7xl mx-auto px-4 grid lg:grid-cols-2 gap-12 items-center"><img src="https://cdn6.ep.dynamics.net/s3/rw-propertyimages/2801-H3125076-99702774__1721265853-49151-DSC07954.jpg?anchor=middlecenter&format=jpg&height=640&maxheight=2841&maxwidth=2841&mode=crop&quality=75&scale=down&width=640" className="rounded-3xl shadow-xl w-full" alt="Modern household appliances"/><div><span className="section-tag">Appliances Repair Solutions</span><h2 className="section-heading">Your Repair, Our Priority!</h2><div className="gold-bar"/><p className="text-appliance-500 mb-6">We help Durban homeowners and businesses get essential appliances working again with professional diagnosis and repair support. Book by phone, WhatsApp or the online request form.</p>{['Fridges & freezers','Washing machines','Ovens & stoves','Dishwashers','Air conditioners','Selected commercial appliances'].map(x=><div key={x} className="flex gap-2 items-center mb-2"><CheckCircle size={17} className="text-amber-500"/><span>{x}</span></div>)}<div className="mt-8 flex gap-3 flex-wrap"><a href="tel:+27756294825" className="btn-gold"><Phone size={16}/> Call Now</a><Link to="/contact" className="btn-gold">Book a Repair</Link></div></div></div></section></div>}
