import { Link } from 'react-router-dom';
import { ShieldCheck,Wrench,Clock3,BadgeDollarSign,ArrowRight,Phone,CheckCircle } from 'lucide-react';
import HeroSlider from '../components/HeroSlider';

const services=[
['Fridge & Freezer Repairs','https://www.bestchoiceappliancerepairs.co.za/images/best_choice_hero.jpg','Cooling faults, leaks, thermostats, compressors, fans and door seals.'],
['Washing Machine Repairs','https://fortune.com/img-assets/wp-content/uploads/2016/01/appliances-2-sa2-copy-copy.jpg?q=75&w=1440','Drainage, spin-cycle, pump, motor, belt, bearing and electrical faults.'],
['TV & Electronics Repairs','https://etimg.etb2bimg.com/thumb/msid-126394933%2Cwidth-1200%2Cheight-900%2Cresizemode-4/.jpg','Selected LED, LCD, Smart TV and electronic display faults, subject to model and parts availability.'],
['Oven & Stove Repairs','https://www.electromart.com.gh/wp-content/uploads/2024/09/Nene-Photgraphy7681-scaled.jpg','Heating elements, ignition, temperature controls and electrical faults.'],
['Microwave Repairs','https://b2blogger.com/pressroom/upload_images/2-1.JPG','Diagnosis and repairs for selected microwave faults and electronic controls.'],
['Dishwasher & Laundry Appliances','https://www.bestchoiceappliancerepairs.co.za/images/best_choice_hero.jpg','Dishwashers, washing machines and related household appliance faults.']];

export default function Home(){return <div className="page-enter"><HeroSlider/><section className="bg-appliance-900 py-6"><div className="max-w-7xl mx-auto px-4 grid grid-cols-2 md:grid-cols-4 gap-5 text-white">{[[Wrench,'Expert Technicians'],[Clock3,'Fast Durban Response'],[ShieldCheck,'Reliable Repairs'],[BadgeDollarSign,'Affordable Pricing']].map(([I,t]:any)=><div className="flex gap-3 items-center" key={t}><I className="text-amber-400"/><span className="text-sm font-semibold">{t}</span></div>)}</div></section><section className="py-20 bg-appliance-50"><div className="max-w-7xl mx-auto px-4"><div className="text-center mb-12"><span className="section-tag">What We Repair</span><h2 className="section-heading text-center">Professional Appliance Repair Services</h2><div className="gold-bar mx-auto"/><p className="text-appliance-500 max-w-2xl mx-auto">Appliances Repair Solutions repairs household appliances and selected electronics across Durban and surrounding areas.</p></div><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-6">{services.map(([title,img,desc])=><Link to="/services" key={title} className="bg-white rounded-2xl overflow-hidden shadow-sm hover:shadow-xl transition"><img src={img} alt={title} className="w-full h-48 object-cover"/><div className="p-5"><h3 className="font-bold text-lg">{title}</h3><p className="text-appliance-500 text-sm mt-2">{desc}</p><span className="text-amber-500 text-sm font-semibold inline-flex gap-1 items-center mt-3">Learn More <ArrowRight size={14}/></span></div></Link>)}</div></div></section><section className="py-20 bg-white"><div className="max-w-7xl mx-auto px-4 grid lg:grid-cols-2 gap-12 items-center"><img src="https://etimg.etb2bimg.com/thumb/msid-126394933%2Cwidth-1200%2Cheight-900%2Cresizemode-4/.jpg" className="rounded-3xl shadow-xl w-full" alt="Refrigerator washing machines television and household appliances"/><div><span className="section-tag">Appliances Repair Solutions</span><h2 className="section-heading">Your Repair, Our Priority!</h2><div className="gold-bar"/><p className="text-appliance-500 mb-6">We help Durban homeowners and businesses get essential appliances and selected electronics working again with professional diagnosis and repair support.</p>{['Fridges & freezers','Washing machines','TVs & selected electronics','Ovens & stoves','Microwaves','Dishwashers'].map(x=><div key={x} className="flex gap-2 items-center mb-2"><CheckCircle size={17} className="text-amber-500"/><span>{x}</span></div>)}<div className="mt-8 flex gap-3 flex-wrap"><a href="tel:+27756294825" className="btn-gold"><Phone size={16}/> Call Now</a><Link to="/contact" className="btn-gold">Book a Repair</Link></div></div></div></section></div>}
