import { Link } from 'react-router-dom';
import { ShieldCheck,Wrench,Clock3,BadgeDollarSign,ArrowRight,Phone,CheckCircle } from 'lucide-react';
import HeroSlider from '../components/HeroSlider';
const services=[
['Fridge & Freezer Repairs','https://fridgeappliancerepairs.simdif.com/images/public/sd_68b228f45ff9c.jpg?no_cache=1756513562','Cooling faults, leaks, thermostats, compressors, fans and door seals.'],
['Washing Machine Repairs','https://www.smartappliance.co.za/wp-content/uploads/2022/10/local-seo-1024x683.jpg','Drainage, spin-cycle, pump, motor, belt, bearing and electrical faults.'],
['Oven & Stove Repairs','https://appliancesrepairsmakkah.shop/wp-content/uploads/2025/07/orig-8.jpeg','Heating elements, ignition, temperature controls and electrical faults.'],
['Dishwasher Repairs','https://img.olx.com.br/images/18/186610497509556.jpg','Drainage, pump, inlet, heating, leaks and control problems.'],
['Air Conditioner Service','https://fridgeappliancerepairs.simdif.com/images/public/sd_68b228f45ff9c.jpg?no_cache=1756513562','Cooling problems, servicing and common air-conditioning faults.'],
['Microwave & Other Appliances','https://s3.ap-south-1.amazonaws.com/cdn.sajilosewa.com/uploads/blogs/69edf01f67a8ed1e84640303.webp','Diagnosis and repairs for selected household and commercial appliances.']];
export default function Home(){return <div className="page-enter"><HeroSlider/><section className="bg-appliance-900 py-6"><div className="max-w-7xl mx-auto px-4 grid grid-cols-2 md:grid-cols-4 gap-5 text-white">{[[Wrench,'Expert Technicians'],[Clock3,'Fast Response'],[ShieldCheck,'Reliable Repairs'],[BadgeDollarSign,'Affordable Pricing']].map(([I,t]:any)=><div className="flex gap-3 items-center" key={t}><I className="text-amber-400"/><span className="text-sm font-semibold">{t}</span></div>)}</div></section><section className="py-20 bg-appliance-50"><div className="max-w-7xl mx-auto px-4"><div className="text-center mb-12"><span className="section-tag">What We Repair</span><h2 className="section-heading text-center">Professional Appliance Repair Services</h2><div className="gold-bar mx-auto"/><p className="text-appliance-500 max-w-2xl mx-auto">Appliances Repair Solutions provides practical repair support for major household appliances, based on the service categories used by the reference Durban appliance-repair site.</p></div><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-6">{services.map(([title,img,desc])=><Link to="/services" key={title} className="bg-white rounded-2xl overflow-hidden shadow-sm hover:shadow-xl transition"><img src={img} alt={title} className="w-full h-48 object-cover"/><div className="p-5"><h3 className="font-bold text-lg">{title}</h3><p className="text-appliance-500 text-sm mt-2">{desc}</p><span className="text-amber-500 text-sm font-semibold inline-flex gap-1 items-center mt-3">Learn More <ArrowRight size={14}/></span></div></Link>)}</div></div></section><section className="py-20 bg-white"><div className="max-w-7xl mx-auto px-4 grid lg:grid-cols-2 gap-12 items-center"><img src="https://durbanactorsstudio.co.za/wp-content/uploads/2024/08/appliance-repairs-Durban-1024x585.jpg" className="rounded-3xl shadow-xl w-full" alt="Appliance repair service"/><div><span className="section-tag">Appliances Repair Solutions</span><h2 className="section-heading">Your Repair, Our Priority!</h2><div className="gold-bar"/><p className="text-appliance-500 mb-6">We help homeowners and businesses get essential appliances working again with professional diagnosis and repair support. Book by phone, WhatsApp or the online request form.</p>{['Fridges & freezers','Washing machines','Ovens & stoves','Dishwashers','Air conditioners','Selected commercial appliances'].map(x=><div key={x} className="flex gap-2 items-center mb-2"><CheckCircle size={17} className="text-amber-500"/><span>{x}</span></div>)}<div className="mt-8 flex gap-3 flex-wrap"><a href="tel:+27756294825" className="btn-gold"><Phone size={16}/> Call Now</a><Link to="/contact" className="btn-gold">Book a Repair</Link></div></div></div></section></div>}
