import { CheckCircle } from 'lucide-react';
const items=[
['Fridge & Freezer Repairs','Cooling failures, refrigerant leaks, compressors, thermostats, fans, noisy operation, water leaks and damaged seals.'],
['Washing Machine Repairs','Machines that will not spin, drain or fill; leaks, pumps, motors, belts, bearings, door locks, sensors and error codes.'],
['Oven & Stove Repairs','Heating-element failures, ignition problems, temperature-control faults, electrical trips and control issues.'],
['Dishwasher Repairs','Blocked drainage, pump failures, inlet faults, heating problems, leaks, spray arms and control-panel faults.'],
['Air Conditioning','Aircon cooling faults, leaking units, servicing and maintenance for selected residential and commercial systems.'],
['Commercial Refrigeration','Selected display fridges, beverage coolers, cold-room and business refrigeration support.'],
['Microwave Repairs','Selected microwave diagnosis and repairs depending on make, model and parts availability.'],
['Other Appliance Faults','Contact us with the appliance brand, model and symptoms and we will advise whether we can assist.']];
export default function Services(){return <div className="page-enter pt-24"><section className="py-20 bg-appliance-900 text-center text-white"><span className="section-tag text-amber-400">What We Do</span><h1 className="text-4xl md:text-5xl font-bold">Appliance Repair Services</h1><p className="text-appliance-300 mt-4 max-w-2xl mx-auto px-4">Repairs for homes, rental properties, offices and businesses across the service area.</p></section><section className="py-20 bg-appliance-50"><div className="max-w-6xl mx-auto px-4 grid md:grid-cols-2 gap-6">{items.map(([t,d])=><div key={t} className="bg-white rounded-2xl p-7 shadow-sm"><h2 className="font-bold text-xl mb-3">{t}</h2><p className="text-appliance-500">{d}</p><div className="flex items-center gap-2 text-sm mt-4 text-appliance-700"><CheckCircle className="text-amber-500" size={17}/> Diagnosis before repair</div></div>)}</div></section><section className="py-16 bg-amber-500 text-center"><h2 className="text-3xl font-bold text-white">Need an Appliance Repaired?</h2><p className="text-amber-100 my-4">Call or WhatsApp us on +27 75 629 4825.</p><a className="inline-block bg-white text-amber-600 px-8 py-3 rounded-xl font-bold" href="tel:+27756294825">Call Now</a></section></div>}
