import { useState, useEffect } from 'react';
import { ChevronLeft, ChevronRight, Phone, FileText } from 'lucide-react';

const slides=[
{image:'https://etimg.etb2bimg.com/thumb/msid-126394933%2Cwidth-1200%2Cheight-900%2Cresizemode-4/.jpg',tag:'FAST • RELIABLE • PROFESSIONAL',heading:'Expert Appliance Repairs',highlight:'Across Durban',sub:'Professional repairs for refrigerators, freezers, washing machines, TVs, ovens, stoves, microwaves and dishwashers.'},
{image:'https://www.bestchoiceappliancerepairs.co.za/images/best_choice_hero.jpg',tag:'HOME & BUSINESS',heading:'We Repair Major',highlight:'Household Appliances',sub:'Practical repair solutions for fridges, laundry appliances, cooking appliances, dishwashers and selected electronics.'},
{image:'https://www.electromart.com.gh/wp-content/uploads/2024/09/Nene-Photgraphy7681-scaled.jpg',tag:'BOOK A REPAIR',heading:'Get Your Appliance',highlight:'Working Again',sub:'Tell us the appliance, fault and your Durban location. Our team will contact you to arrange assistance.'}
];

export default function HeroSlider(){const [current,setCurrent]=useState(0); useEffect(()=>{const x=setInterval(()=>setCurrent(v=>(v+1)%slides.length),6000);return()=>clearInterval(x)},[]); const s=slides[current];return <section className="relative w-full h-screen min-h-[620px] max-h-[900px] overflow-hidden">{slides.map((x,i)=><img key={i} src={x.image} className={`absolute inset-0 w-full h-full object-cover transition-opacity duration-1000 ${i===current?'opacity-100':'opacity-0'}`} alt="Household appliances"/>)}<div className="absolute inset-0 bg-gradient-to-r from-black/85 via-black/60 to-black/20"/><div className="relative z-20 h-full flex items-center"><div className="max-w-7xl mx-auto px-6 w-full"><div className="max-w-2xl"><span className="inline-block px-3 py-1.5 rounded-full border border-blue-400/50 bg-blue-500/15 text-blue-200 text-xs font-bold tracking-widest mb-5">{s.tag}</span><h1 className="text-white text-4xl sm:text-5xl md:text-6xl font-bold leading-tight">{s.heading}<br/><span className="text-amber-400">{s.highlight}</span></h1><p className="text-white/80 text-lg mt-5 max-w-xl">{s.sub}</p><div className="flex flex-wrap gap-3 mt-8"><a href="tel:+27756294825" className="btn-gold"><Phone size={16}/> Call 075 629 4825</a><a href="/contact" className="inline-flex items-center gap-2 px-5 py-3 border-2 border-white/50 text-white rounded-lg font-semibold"><FileText size={16}/> Request Repair</a></div></div></div></div><button onClick={()=>setCurrent((current-1+slides.length)%slides.length)} className="absolute z-30 left-4 top-1/2 text-white p-3 bg-black/30 rounded-full"><ChevronLeft/></button><button onClick={()=>setCurrent((current+1)%slides.length)} className="absolute z-30 right-4 top-1/2 text-white p-3 bg-black/30 rounded-full"><ChevronRight/></button></section>}
